delete from public.menu_items
where category = 'pastries';

insert into public.menu_items (
  id,
  "nameAr",
  "nameEn",
  category,
  price,
  calories,
  image,
  sizes,
  "isAvailable",
  "sortOrder",
  "createdAt",
  "updatedAt"
) values
  (
    'pt-1',
    'سبانخ',
    'Spinach Pastry',
    'pastries',
    7,
    428,
    '/menu/pastries/spinach.jpg',
    '[{"name":"صغير","price":7},{"name":"وسط","price":11},{"name":"كبير","price":17}]'::jsonb,
    true,
    900,
    now(),
    now()
  ),
  (
    'pt-2',
    'اللحم',
    'Meat Pastry',
    'pastries',
    10,
    479,
    '/menu/pastries/meat.jpg',
    '[{"name":"صغير","price":10},{"name":"وسط","price":16},{"name":"كبير","price":22}]'::jsonb,
    true,
    901,
    now(),
    now()
  ),
  (
    'pt-3',
    'سائل الجبن',
    'Liquid Cheese Pastry',
    'pastries',
    8,
    805,
    '/menu/pastries/liquid-cheese.jpg',
    '[{"name":"صغير","price":8},{"name":"وسط","price":13},{"name":"كبير","price":18}]'::jsonb,
    true,
    902,
    now(),
    now()
  ),
  (
    'pt-4',
    'عش البلبل',
    'Nightingale''s Nest',
    'pastries',
    9,
    927,
    '/menu/pastries/ash-albulbul.jpg',
    '[{"name":"صغير","price":9},{"name":"وسط","price":17},{"name":"كبير","price":23}]'::jsonb,
    true,
    903,
    now(),
    now()
  ),
  (
    'pt-5',
    'لبنة',
    'Labaneh Pastry',
    'pastries',
    8,
    578,
    '/menu/pastries/labneh.jpg',
    '[{"name":"صغير","price":8},{"name":"وسط","price":13},{"name":"كبير","price":18}]'::jsonb,
    true,
    904,
    now(),
    now()
  ),
  (
    'pt-6',
    'الدجاج',
    'Chicken Pastry',
    'pastries',
    8,
    709,
    '/menu/pastries/chicken.jpg',
    '[{"name":"صغير","price":8},{"name":"وسط","price":13},{"name":"كبير","price":18}]'::jsonb,
    true,
    905,
    now(),
    now()
  ),
  (
    'pt-7',
    'لبنة زيتون',
    'Labaneh Olive Pastry',
    'pastries',
    9,
    653,
    '/menu/pastries/labneh-olive.jpg',
    '[{"name":"صغير","price":9},{"name":"وسط","price":16},{"name":"كبير","price":22}]'::jsonb,
    true,
    906,
    now(),
    now()
  ),
  (
    'pt-8',
    'محمرة',
    'Muhammara Pastry',
    'pastries',
    7,
    619,
    '/menu/pastries/muhammara.jpg',
    '[{"name":"صغير","price":7},{"name":"وسط","price":12},{"name":"كبير","price":17}]'::jsonb,
    true,
    907,
    now(),
    now()
  ),
  (
    'pt-9',
    'زعتر',
    'Zaatar Pastry',
    'pastries',
    7,
    500,
    '/menu/pastries/zaatar.jpg',
    '[{"name":"صغير","price":7},{"name":"وسط","price":12},{"name":"كبير","price":17}]'::jsonb,
    true,
    908,
    now(),
    now()
  ),
  (
    'pt-10',
    'بيض بالجبن',
    'Egg Cheese Pastry',
    'pastries',
    9,
    676,
    '/menu/pastries/egg-cheese.jpg',
    '[{"name":"صغير","price":9},{"name":"وسط","price":16},{"name":"كبير","price":22}]'::jsonb,
    true,
    909,
    now(),
    now()
  );
