delete from public.menu_items
where category = 'pasta';

insert into public.menu_items (
  id,
  "nameAr",
  "nameEn",
  category,
  price,
  calories,
  image,
  sizes,
  "isAvailable",
  "sortOrder",
  "createdAt",
  "updatedAt"
) values
  (
    'ps-1',
    'باستا خضار',
    'Vegetable Pasta',
    'pasta',
    10,
    330,
    '/menu/pasta/vegetables.jpg',
    '[{"name":"صغير","price":10},{"name":"كبير","price":20}]'::jsonb,
    true,
    800,
    now(),
    now()
  ),
  (
    'ps-2',
    'باستا الفريدو',
    'Alfredo Pasta',
    'pasta',
    15,
    400,
    '/menu/pasta/alfredo.jpg',
    '[{"name":"صغير","price":15},{"name":"كبير","price":25}]'::jsonb,
    true,
    801,
    now(),
    now()
  ),
  (
    'ps-3',
    'مكرونة بشاميل',
    'Bechamel Pasta',
    'pasta',
    15,
    435,
    '/menu/pasta/bechamel.jpg',
    '[{"name":"صغير","price":15},{"name":"كبير","price":25}]'::jsonb,
    true,
    802,
    now(),
    now()
  ),
  (
    'ps-4',
    'باستا جمبري',
    'Shrimp Pasta',
    'pasta',
    20,
    460,
    '/menu/pasta/shrimp.jpg',
    '[{"name":"صغير","price":20},{"name":"كبير","price":30}]'::jsonb,
    true,
    803,
    now(),
    now()
  ),
  (
    'ps-5',
    'باستا جبن',
    'Cheese Pasta',
    'pasta',
    10,
    450,
    '/menu/pasta/cheese.jpg',
    '[{"name":"صغير","price":10},{"name":"كبير","price":20}]'::jsonb,
    true,
    804,
    now(),
    now()
  ),
  (
    'ps-6',
    'باستا فوتشيني',
    'Fettuccine Pasta',
    'pasta',
    15,
    750,
    '/menu/pasta/fettuccine.jpg',
    '[{"name":"صغير","price":15},{"name":"كبير","price":25}]'::jsonb,
    true,
    805,
    now(),
    now()
  ),
  (
    'ps-7',
    'باستا بولينيس',
    'Bolognese Pasta',
    'pasta',
    20,
    430,
    '/menu/pasta/bolognese.jpg',
    '[{"name":"صغير","price":20},{"name":"كبير","price":31}]'::jsonb,
    true,
    806,
    now(),
    now()
  ),
  (
    'ps-8',
    'باستا البيني',
    'Penne Pasta',
    'pasta',
    10,
    320,
    '/menu/pasta/penne.jpg',
    '[{"name":"صغير","price":10},{"name":"كبير","price":20}]'::jsonb,
    true,
    807,
    now(),
    now()
  ),
  (
    'ps-9',
    'باستا لازانيا',
    'Lasagna Pasta',
    'pasta',
    15,
    470,
    '/menu/pasta/lasagna.jpg',
    '[{"name":"صغير","price":15},{"name":"كبير","price":25}]'::jsonb,
    true,
    808,
    now(),
    now()
  );
