delete from public.menu_items
where category = 'pizza';

insert into public.menu_items (
  id,
  "nameAr",
  "nameEn",
  category,
  price,
  calories,
  image,
  sizes,
  "isAvailable",
  "sortOrder",
  "createdAt",
  "updatedAt"
) values
  (
    'pz-1',
    'سبيشل شاورما',
    'Special Shawarma Pizza',
    'pizza',
    13,
    613,
    '/menu/pizza/special-shawarma.jpeg',
    '[{"name":"صغير","price":13},{"name":"وسط","price":24},{"name":"كبير","price":29}]'::jsonb,
    true,
    700,
    now(),
    now()
  ),
  (
    'pz-2',
    'مشكل',
    'Mixed Pizza',
    'pizza',
    13,
    576,
    '/menu/pizza/mixed.jpeg',
    '[{"name":"صغير","price":13},{"name":"وسط","price":24},{"name":"كبير","price":29}]'::jsonb,
    true,
    701,
    now(),
    now()
  ),
  (
    'pz-3',
    'شاورما',
    'Shawarma Pizza',
    'pizza',
    13,
    613,
    '/menu/pizza/shawarma.jpeg',
    '[{"name":"صغير","price":13},{"name":"وسط","price":24},{"name":"كبير","price":29}]'::jsonb,
    true,
    702,
    now(),
    now()
  ),
  (
    'pz-4',
    'دجاج',
    'Chicken Pizza',
    'pizza',
    10,
    576,
    '/menu/pizza/chicken.jpeg',
    '[{"name":"صغير","price":10},{"name":"وسط","price":17},{"name":"كبير","price":23}]'::jsonb,
    true,
    703,
    now(),
    now()
  ),
  (
    'pz-5',
    'خضار',
    'Vegetables Pizza',
    'pizza',
    9,
    461,
    '/menu/pizza/vegetables.jpeg',
    '[{"name":"صغير","price":9},{"name":"وسط","price":16},{"name":"كبير","price":22}]'::jsonb,
    true,
    704,
    now(),
    now()
  ),
  (
    'pz-6',
    'سبيشل ماكولاتي',
    'Makolaty Special Pizza',
    'pizza',
    13,
    693,
    '/menu/pizza/makolaty-special.jpeg',
    '[{"name":"صغير","price":13},{"name":"وسط","price":24},{"name":"كبير","price":29}]'::jsonb,
    true,
    705,
    now(),
    now()
  ),
  (
    'pz-7',
    'ببروني',
    'Pepperoni Pizza',
    'pizza',
    13,
    428,
    '/menu/pizza/pepperoni.jpeg',
    '[{"name":"صغير","price":13},{"name":"وسط","price":24},{"name":"كبير","price":29}]'::jsonb,
    true,
    706,
    now(),
    now()
  ),
  (
    'pz-8',
    'دجاج رانش',
    'Chicken Ranch Pizza',
    'pizza',
    13,
    470,
    '/menu/pizza/chicken-ranch.jpeg',
    '[{"name":"صغير","price":13},{"name":"وسط","price":24},{"name":"كبير","price":29}]'::jsonb,
    true,
    707,
    now(),
    now()
  ),
  (
    'pz-9',
    'جمبري',
    'Shrimp Pizza',
    'pizza',
    15,
    709,
    '/menu/pizza/shrimp.jpeg',
    '[{"name":"صغير","price":15},{"name":"وسط","price":25},{"name":"كبير","price":30}]'::jsonb,
    true,
    708,
    now(),
    now()
  ),
  (
    'pz-10',
    'مارجريتا جبن',
    'Margherita Cheese Pizza',
    'pizza',
    10,
    459,
    '/menu/pizza/margherita-cheese.jpeg',
    '[{"name":"صغير","price":10},{"name":"وسط","price":17},{"name":"كبير","price":23}]'::jsonb,
    true,
    709,
    now(),
    now()
  ),
  (
    'pz-11',
    'باربكيو',
    'Barbecue Pizza',
    'pizza',
    13,
    613,
    '/menu/pizza/barbecue.jpeg',
    '[{"name":"صغير","price":13},{"name":"وسط","price":24},{"name":"كبير","price":29}]'::jsonb,
    true,
    710,
    now(),
    now()
  );
